"""add ad slot poster

Revision ID: bfda4a92997d
Revises: 288bfacacd80
Create Date: 2026-08-17 13:32:52.790127
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bfda4a92997d'
down_revision: Union[str, None] = '288bfacacd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: the table already holds rows, and a NOT NULL
    # column without one is rejected. It is dropped afterwards so the ORM
    # default stays the single source of truth.
    op.add_column(
        'ad_slots',
        sa.Column('poster_url', sa.String(length=500), nullable=False, server_default=''),
    )
    op.add_column(
        'ad_slots',
        sa.Column('poster_alt', sa.String(length=200), nullable=False, server_default=''),
    )
    op.alter_column('ad_slots', 'poster_url', server_default=None)
    op.alter_column('ad_slots', 'poster_alt', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_slots', 'poster_alt')
    op.drop_column('ad_slots', 'poster_url')
    # ### end Alembic commands ###
